### ISSUE TITLE
Compiler crash compiling readonly attributes in cython classes

### ISSUE THREAD

**Issue by Timtam** [mingwpy/mingwpy#14]
[crash.txt](https://github.com/mingwpy/mingwpy/files/177664/crash.txt)

It appears that mingwpy always crashes when compiling cython classes containing readonly attributes.

The following minimalistic cython example states this:

crash.pxd

``` cython
cdef class CrashClass:
  cdef readonly int __attribute
```

crash.pyx

``` cython
cdef class CrashClass:
  pass
```

``` python
import pyximport
pyximport.install()
import crash
```

```
C:\Users\***\WinPython-32bit-2.7.10.2\settings\.pyxbld\temp.win32-2.7\Release\pyrex\crash.c:477:18: error: expected '(' before ';' token
   int __attribute;
                  ^
C:\Users\***\WinPython-32bit-2.7.10.2\settings\.pyxbld\temp.win32-2.7\Release\pyrex\crash.c: In function '__pyx_pf_5crash_10CrashClass_11__attribute___get__':
C:\Users\***\WinPython-32bit-2.7.10.2\settings\.pyxbld\temp.win32-2.7\Release\pyrex\crash.c:611:50: error: expected identifier before '__attribute'
   __pyx_t_1 = __Pyx_PyInt_From_int(__pyx_v_self->__attribute); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 2, __pyx_L1_error)
                                                  ^
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\***\WinPython-32bit-2.7.10.2\python-2.7.10\lib\site-packages\cython-0.24a0-py2.7-win32.egg\pyximport\pyximport.py", line 445, in load_module
    language_level=self.language_level)
  File "C:\Users\***\WinPython-32bit-2.7.10.2\python-2.7.10\lib\site-packages\cython-0.24a0-py2.7-win32.egg\pyximport\pyximport.py", line 234, in load_module
    exec("raise exc, None, tb", {'exc': exc, 'tb': tb})
  File "C:\Users\***\WinPython-32bit-2.7.10.2\python-2.7.10\lib\site-packages\cython-0.24a0-py2.7-win32.egg\pyximport\pyximport.py", line 216, in load_module
    inplace=build_inplace, language_level=language_level)
  File "C:\Users\***\WinPython-32bit-2.7.10.2\python-2.7.10\lib\site-packages\cython-0.24a0-py2.7-win32.egg\pyximport\pyximport.py", line 192, in build_module
    reload_support=pyxargs.reload_support)
  File "C:\Users\***\WinPython-32bit-2.7.10.2\python-2.7.10\lib\site-packages\cython-0.24a0-py2.7-win32.egg\pyximport\pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()
  File "C:\Users\***\WinPython-32bit-2.7.10.2\python-2.7.10\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Users\***\WinPython-32bit-2.7.10.2\python-2.7.10\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Users\***\WinPython-32bit-2.7.10.2\python-2.7.10\lib\site-packages\cython-0.24a0-py2.7-win32.egg\Cython\Distutils\build_ext.py", line 164, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\***\WinPython-32bit-2.7.10.2\python-2.7.10\lib\distutils\command\build_ext.py", line 337, in run
    self.build_extensions()
  File "C:\Users\***\WinPython-32bit-2.7.10.2\python-2.7.10\lib\site-packages\cython-0.24a0-py2.7-win32.egg\Cython\Distutils\build_ext.py", line 172, in build_extensions
    self.build_extension(ext)
  File "C:\Users\***\WinPython-32bit-2.7.10.2\python-2.7.10\lib\distutils\command\build_ext.py", line 496, in build_extension
    depends=ext.depends)
  File "C:\Users\***\WinPython-32bit-2.7.10.2\python-2.7.10\lib\distutils\ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "C:\Users\***\WinPython-32bit-2.7.10.2\python-2.7.10\lib\distutils\cygwinccompiler.py", line 166, in _compile
    raise CompileError, msg
ImportError: Building module crash failed: ["CompileError: command 'C:\\\\Users\\\\**\\\\WinPython-32bit-2.7.10.2\\\\python-2.7.10\\\\Scripts\\\\gcc.exe' failed with exit status 1\n"]
```

used

```
gcc.exe (i686-win32-sjlj-rev201506, mingwpy build) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

and

cython 0.23.4 and also the latest cython master.

latest cython master compiles this example down to the attached c file.
Any ideas?

**Comment by Timtam** [comment]
it appears that i can't submit the file from work, so I will do this later from home. stay tuned :)

**Comment by ogrisel** [comment]
I edited your report to use triple backticks escapes for the code block to make the report readable.

**Comment by ogrisel** [comment]
Actually this is not a mingwpy bug as this triggers an error with clang under osx and gcc under linux too. I think the `__atribute` name is a reserved keyword and the generated C code is invalid. Here is a minimalistic Cython program (no need for a pxd file):

crash.pyx:

``` cython
cdef class CrashClass:
  cdef readonly int __attribute
```

If you change `__attribute` to `__something_else` it compiles correctly. I agree that the fact that cython accepts to generate invalid C code without complaining is probably a Cython bug.

Closing.

**Comment by carlkl** [comment]
Thanks for that insight.
